[tool.poetry]
name = "cdhdashboard"
version = "0.1.0"
description = "The CDH Value Dashboard Application is an open-source prototype designed to provide customizable metrics and insights for linking marketing actions to business outcomes, such as customer lifetime value (CLV) and conversion rates."
authors = ["Grigoriy Sen <grigoriy.sen@pega.com>"]
license = "MIT"
readme = "README.md"
exclude = [
    "value_dashboard/config"
]
packages = [
    {include = "*", from="."},
    {include = "value_dashboard", from="."}
]

[tool.poetry.dependencies]
python = ">3.10,<3.12"
numpy = ">1.23.1, <2.0.0"
polars = "^1.16.0"
polars-ds = "^0.7.0"
pytdigest = "^0.1.4"
pandas = "^2.2.0"
plotly = "^6.0.0"
streamlit = "^1.41.1"
scikit-learn = "^1.5.1"
scipy = "^1.10.1"
st-pages = "^1.0.1"
st-theme = "^1.2.3"
streamlit-dynamic-filters = "^0.1.9"
streamlit-option-menu = "^0.4.0"
streamlit-dimensions = "^0.0.1"
streamlit-autorefresh = "^1.0.1"
streamlit-tags = "^1.2.8"
streamlit-sortables = "^0.3.1"
pillow = "^10.4.0"
tomlkit = "^0.13.2"
psutil = "^6.1.1"
hvplot = "^0.11.0"
pandasai = {version = "^3.0.0b2", optional = true}
kaleido = {version = "*", optional = true}

[tool.poetry.extras]
chat = ["pandasai", "kaleido"]

[tool.poetry.scripts]
cdhdashboard = "value_dashboard.utils.cli:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
